#version: "3"
services:
  api:
    build: ./api
    command: npm start
    environment:
      - PORT=3001
      - HOST=localhost
      - MONGO_URL=mongodb://api_db:27017/api
    depends_on:
      - api_db
  api_db:
    image: mongo:latest
    volumes:
      - mongodb_api:/data/db
  frontend:
    build: 
      context: ./frontend/frontend
      dockerfile: Dockerfile.prod
    container_name: realworld-docker-frontend
    command: serve -s build -l 3000
    restart: unless-stopped
    stdin_open: true
    tty: true
  nginx:
    image: nginx:latest
    container_name: websystem-docker-nginx
    volumes:
      - ./nginx/nginx.prod.conf:/etc/nginx/conf.d/nginx.conf
    ports:
      - "80:80"
    depends_on:
      - frontend
      - api
volumes:
  mongodb_api: