FROM node:20-alpine3.17
# створення робочої папки застосунку
WORKDIR /usr/src/app
# копіювання package.json та встановлення залежностей
COPY package*.json ./
RUN npm install
# копіюємо вихідний код в робочу папку
COPY . .

RUN npm run build
RUN npm install -g serve

CMD ["serve", "-s", "build", "-l", "3000"]